---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: portfolio-service
spec:
  hosts:
  - portfolio-service
  http:
  - route:
    - destination:
        host: portfolio-service
        subset: "v1"
      weight: 100
    retries:
      attempts: 3
      perTryTimeout: 2s
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: portfolio-service
spec:
  host: portfolio-service
  trafficPolicy:
    loadBalancer:
      simple: RANDOM
    connectionPool:
      tcp:
        maxConnections: 30
        connectTimeout: 100ms
      http:
        http1MaxPendingRequests: 10
        http2MaxRequests: 100
        maxRequestsPerConnection: 10
        maxRetries: 5
    outlierDetection:
      consecutiveErrors: 5
      interval: 30s
      baseEjectionTime: 60s
  subsets:
    - name: v1
      labels:
        version: "v1"

