apiVersion: skaffold/v2beta1
kind: Config
build:
  artifacts:
    - image: config
      context: ../config-service
      buildpack:
        builder: humourmind/cnb-java-builder-tiny:0.7.2
        # forcePull: false
    - image: gateway
      context: ../gateway-service
      buildpack:
        builder: humourmind/cnb-java-builder-tiny:0.7.2
        # forcePull: false
    - image: portfolio
      context: ../portfolio-service
      buildpack:
        builder: humourmind/cnb-java-builder-tiny:0.7.2
        # forcePull: false
    - image: accounts
      context: ../accounts-service
      buildpack:
        builder: humourmind/cnb-java-builder-tiny:0.7.2
        # forcePull: false
    - image: quotes
      context: ../quotes-service
      buildpack:
        builder: humourmind/cnb-java-builder-tiny:0.7.2
        # forcePull: false
    - image: user
      context: ../user-service
      buildpack:
        builder: humourmind/cnb-java-builder-tiny:0.7.2
        # forcePull: false        
    - image: web
      context: ../web-ui
      buildpack:
        builder: humourmind/cnb-java-builder-tiny:0.7.2
        # forcePull: false
  tagPolicy:
    envTemplate:
      template: 'harbor.sys.humourmind.com/wo/{{.IMAGE_NAME}}:1.0'
  local:
    push: true
deploy:
  kustomize: {}