---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: portfolio-build-cache
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
---
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: portfolio
  labels:
    app: portfolio
spec:
  template:
    metadata:
      name: portfolio
  runLatest:
    configuration:
      build:
        serviceAccountName: build-bot
        source:
          git:
            url: https://github.com/srinivasa-vasu/pivotal-bank-demo.git
            revision: pks_1.0
          subPath: portfolio-service
        template:
          name: jib-gradle
          arguments:
          - name: IMAGE
            value: $REGISTRY/portfolio-service
        volumes:
          - name: persistent-cache
            persistentVolumeClaim:
              claimName: portfolio-build-cache
      revisionTemplate:
        metadata:
          name: portfolio
          annotations:
            # this prevents from scale to zero
            autoscaling.knative.dev/minScale: "1"
          labels:
            app: portfolio
            knative.dev/type: app
        spec:
          metadata:
            name: portfolio
            labels:
              app: portfolio
              version: v1
          container:
            image: $REGISTRY/portfolio-service
            env:
            - name: SPRING_CLOUD_CONFIG_LABEL
              value: pks_1.0
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://traderdb:3306/traderdb?useUnicode=true&characterEncoding=utf8&useSSL=false
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_PROFILES_ACTIVE
              value: cloud
#            - name: SPRING_CLOUD_CONFIG_URI
#              value: http://config-service
  traffic:
    - tag: portfolio
      percent: 100
      latestRevision: true

