---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: web-build-cache
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
---
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: web
  labels:
    app: web
spec:
  template:
    metadata:
      name: web
  runLatest:
    configuration:
      build:
        serviceAccountName: build-bot
        source:
          git:
            url: https://github.com/srinivasa-vasu/pivotal-bank-demo.git
            revision: pks_1.0
          subPath: web
        template:
          name: jib-gradle
          arguments:
          - name: IMAGE
            value: humourmind/web-service
        volumes:
          - name: persistent-cache
            persistentVolumeClaim:
              claimName: web-build-cache
      revisionTemplate:
        metadata:
          name: web
          annotations:
            # this prevents from scale to zero
            autoscaling.knative.dev/minScale: "1"
          labels:
            app: web
            knative.dev/type: app
        spec:
          metadata:
            name: web
            labels:
              app: web
              version: v1
          container:
            image: humourmind/web-service
            env:
            - name: SPRING_CLOUD_CONFIG_LABEL
              value: pks_1.0
            - name: SPRING_PROFILES_ACTIVE
              value: cloud
#            - name: SPRING_CLOUD_CONFIG_URI
#              value: http://config-service
  traffic:
    - tag: web
      percent: 100
      latestRevision: true

