apiVersion: v1
kind: ConfigMap
metadata:
  name: config-props
data:
  SPRING_PROFILES_ACTIVE: cloud
  SPRING_CLOUD_CONFIG_LABEL: observability_1.0
  MANAGEMENT_METRICS_EXPORT_WAVEFRONT_API_TOKEN: <to_be_filled>
  MANAGEMENT_METRICS_EXPORT_WAVEFRONT_URI: https://surf.wavefront.com
  MANAGEMENT_METRICS_EXPORT_WAVEFRONT_STEP: 30s
  MANAGEMENT_METRICS_EXPORT_WAVEFRONT_GLOBAL_PREFIX: hm-bank
  MANAGEMENT_METRICS_EXPORT_WAVEFRONT_SOURCE: hm-bank
  IEX_CLOUD_API_TOKEN: <to_be_filled>