---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    app: "config"
    kind: "k8s-native"
    version: "1.0"
  name: "config"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "config"
      kind: "k8s-native"
      version: "1.0"
  template:
    metadata:
      labels:
        app: "config"
        kind: "k8s-native"
        version: "1.0"
    spec:
      serviceAccount: boot-sa
      containers:
      - name: "config"
        envFrom:
          - configMapRef: 
              name: config-props
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 10"]
        image: "harbor.sys.humourmind.com/wo/config:1.0"
        imagePullPolicy: "Always"
        # livenessProbe:
        #   failureThreshold: 3
        #   httpGet:
        #     path: "/actuator/health/liveness"
        #     port: 8080
        #     scheme: "HTTP"
        #   initialDelaySeconds: 0
        #   periodSeconds: 30
        #   successThreshold: 1
        #   timeoutSeconds: 10
        ports:
        - containerPort: 8080
          name: "web"
          protocol: "TCP"
        # readinessProbe:
        #   failureThreshold: 3
        #   httpGet:
        #     path: "/actuator/health/readiness"
        #     port: 8080
        #     scheme: "HTTP"
        #   initialDelaySeconds: 0
        #   periodSeconds: 30
        #   successThreshold: 1
        #   timeoutSeconds: 10
---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: "config-service"
    version: "1.0"
  name: "config-service"
spec:
  ports:
  - name: "web"
    port: 80
    targetPort: 8080
  selector:
    app: "config"
    version: "1.0"
  type: "ClusterIP"          