pivotal:
  quotesService:
    name: gateway-service
  userService:
    name: gateway-service
  accountsService:
    name: gateway-service
  portfolioService:
    name: gateway-service
  analyticsService:
    name: gateway-service
logging:
  level:
     io:
        pivotal: DEBUG
     com:
        netflix: FATAL
     org:
        springframework:
           web: WARN
           cloud: WARN
spring:
  sleuth:
    sampler:
      probability: 1.0
management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
