spring:
  application:
     name: web-service
#eureka:
#  client:
#    registerWithEureka: true
#    registryFetchIntervalSeconds: 10
pivotal:
  summary:
    quotes: 2
    symbols:
      it: ORCL,IBM,INTC,AMD,HPQ,CSCO,AAPL
      fs: JPM,C,MS,BAC,GS,WFC,BK
